package constants

type Operation string

const (
	OPERATION_CREATE_PERMISSION           = "CREATE_PERMISSION"
	OPERATION_DELETE_PERMISSION           = "DELETE_PERMISSION"
	OPERATION_ADD_PERMISSIONS_TO_USER     = "ADD_PERMISSIONS_TO_USER"
	OPERATION_REMOVE_PERMISSIONS_OF_USER  = "REMOVE_PERMISSIONS_OF_USER"
	OPERATION_ADD_PERMISSIONS_TO_GROUP    = "ADD_PERMISSIONS_TO_GROUP"
	OPERATION_REMOVE_PERMISSIONS_OF_GROUP = "REMOVE_PERMISSIONS_OF_GROUP"
	OPERATION_ADD_USER_TO_GROUP           = "ADD_USER_TO_GROUP"
	OPERATION_REMOVE_USER_FROM_GROUP      = "REMOVE_USER_FROM_GROUP"
	OPERATION_CREATE_GROUP                = "CREATE_GROUP"
	OPERATION_DELETE_GROUP                = "DELETE_GROUP"
)
