Name: openauth-local
Build: dev
LogLevel: debug # debug/info/warn/error/panic/fatal
App: MIGRATION # RESTAPP/MIGRATION
CTRL:
  Name: HTTP    # HTTP/GRPC
  HTTP:
    Port: 8000
    GinMode: debug # debug/release
Repository:
  Name: PGSQL # PGSQL
  PGSQL:
    Host: localhost   
    Port: 5432   
    Username: postgres
    Password: 1234
    Database: openauth    
    SSLMode: disable  #disable/require/verify-ca/verify-full  ## Note: disable by default
Migration:
  FilesPath: ./resources/sql/
  Action: UP  # UP/DOWN  
