DROP TABLE IF EXISTS user_permissions;
DROP TABLE IF EXISTS group_permissions;
DROP TABLE IF EXISTS user_groups;
DROP TABLE IF EXISTS "groups";
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS otps;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
